
Para criar um controlador de entrada NGINX básico como DaemonSet, utilize o helm, instalação e arquivos https://helm.sh/ (Tambem disponível na lib do choco)


Com helm instalado basta rodar os comando abaixo em uma maquina com acesso ao cluster.


Linux (bash)

NAMESPACE=ingress-basic

helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
helm repo update

helm install ingress-nginx ingress-nginx/ingress-nginx \
  --create-namespace \
  --namespace $NAMESPACE \
  --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-health-probe-request-path"=/healthz
  --set controller.kind DaemonSet


Windows (PowerShell)


$Namespace = 'ingress-basic'

helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
helm repo update

helm install ingress-nginx ingress-nginx/ingress-nginx `
  --create-namespace `
  --namespace $Namespace `
  --set controller.kind DaemonSet
